Feat/#15 searchfor placeswith searchbar
HongDam-org/TWTW_iOS pull request #24
Opened 2023-10-27 12:06 UTC by dami0806

2023-10-27 22:23 UTC, HJ39 requested changes
굿굿

2023-10-27 22:23 UTC, HJ39 commented on TWTW/TWTW/SearchPlaces/SearchPlaces/SearchPlaces.swift
> +}
주석 달아주세요

2023-10-27 22:23 UTC, HJ39 commented on TWTW/TWTW/SearchPlaces/SearchPlaces/SearchPlaces.swift
> +}
직관적인 이름으로 바꿔주세요

2023-10-27 22:23 UTC, HJ39 commented on TWTW/TWTW/SearchPlaces/SearchPlaces/SearchPlacesMapService.swift
> +            let url = "\(Domain.REST_API)\(SearchPath.placeAndCategory)?query=\(encodedQuery)&page=1&categoryGroupCode=NONE"
이부분 이방식말고 다른방식으로 바꿔보죠

2023-10-27 22:23 UTC, HJ39 commented on TWTW/TWTW/SearchPlaces/SearchPlaces/SearchPlacesMapService.swift
> +                .validate(statusCode: 200..<300)
범위가 너무 넓습니다

2023-10-27 22:23 UTC, HJ39 commented on TWTW/TWTW/SearchPlaces/SearchPlaces/SearchPlacesMapViewController.swift
> +    }()
주석 달아주시고 이름 직관적인 이름으로 변경해주세요

2023-10-27 22:23 UTC, HJ39 commented on TWTW/TWTW/SearchPlaces/SearchPlaces/SearchPlacesMapViewController.swift
> +            .debounce(.milliseconds(300), scheduler: MainScheduler.instance) // 디바운스를 추가하여 입력 지연 처리
debounce처리를 왜 해야하나요?

2023-10-27 22:23 UTC, HJ39 commented on TWTW/TWTW/SearchPlaces/SearchPlaces/SearchPlacesMapViewModel.swift
> +    let selectedCoordinate = PublishRelay<CLLocationCoordinate2D>()
밖에 왜 뺀건가요?

2023-10-27 22:23 UTC, HJ39 commented on TWTW/TWTW/SearchPlaces/SearchPlaces/SearchPlacesMapViewModel.swift
> +            .throttle(.milliseconds(300), scheduler: MainScheduler.instance)
스로틀링이 왜 필요한가요?

2023-10-27 22:23 UTC, HJ39 commented on TWTW/TWTW/SearchPlaces/SearchPlaces/SearchPlacesTableViewCell.swift
> +    private let categoryNameLabel : UILabel = {
이 파일도 주석..

2023-10-27 22:23 UTC, HJ39 commented on TWTW/TWTW/SearchPlaces/SearchPlaces/SearchPlacesMapViewController.swift
> +    let cellIdentifier = "SearchPlacesTableViewCell"
이게 왜 뷰컨에 있나요?

2023-10-28 08:29 UTC, dami0806 commented on TWTW/TWTW/SearchPlaces/SearchPlaces/SearchPlacesMapViewModel.swift
> +            .throttle(.milliseconds(300), scheduler: MainScheduler.instance)
타이핑하는 동안 불필요한 요청을 보내는 방지하려고여 
오타같은 경우나 원하는 검색어가 아닌경우의 비효율을 낮추려고 마지막 입력하고 300밀리초 지난 후 입력 처리하게 했슴다

2023-10-28 08:30 UTC, dami0806 commented on TWTW/TWTW/SearchPlaces/SearchPlaces/SearchPlacesMapViewModel.swift
> +    let selectedCoordinate = PublishRelay<CLLocationCoordinate2D>()
let selectedCoordinate
를 coord에서 사용하려면 함수로사용하면 input(매개 없는)output같은 함수를 만들어서 사용해야 하는데 기능수가 1개면 함수로 만들어서사용할 필요가 없을거 같아서 변수로 썼어요

2023-10-28 08:30 UTC, dami0806 commented on TWTW/TWTW/SearchPlaces/SearchPlaces/SearchPlacesMapViewController.swift
> +    let cellIdentifier = "SearchPlacesTableViewCell"
엥 그러게

2023-10-28 08:34 UTC, dami0806 commented on TWTW/TWTW/SearchPlaces/SearchPlaces/SearchPlacesMapViewController.swift
> +            .debounce(.milliseconds(300), scheduler: MainScheduler.instance) // 디바운스를 추가하여 입력 지연 처리
얘도 타이핑하면서 저 300 milliseconds동안 아무 이벤트 발생 안하고 가장 최근 이벤트만 발행해줘여  급격한 변화로 좀 부자연스러운 UI방지하려고 넣었슴다

2023-10-28 08:39 UTC, dami0806 commented on TWTW/TWTW/SearchPlaces/SearchPlaces/SearchPlaces.swift
> +}
넹

2023-10-28 08:39 UTC, dami0806 commented on TWTW/TWTW/SearchPlaces/SearchPlaces/SearchPlaces.swift
> +}
넹

2023-10-28 08:40 UTC, dami0806 commented on TWTW/TWTW/SearchPlaces/SearchPlaces/SearchPlacesTableViewCell.swift
> +    private let categoryNameLabel : UILabel = {
넹

2023-10-28 08:40 UTC, dami0806 commented on TWTW/TWTW/SearchPlaces/SearchPlaces/SearchPlacesMapService.swift
> +                .validate(statusCode: 200..<300)
누ㅔ

2023-10-30 00:57 UTC, HJ39 commented on TWTW/TWTW/SearchPlaces/SearchPlaces/SearchPlacesMapViewController.swift
> +    let searchPlacesTableViewCell = SearchPlacesTableViewCell()
이렇게 말고 
SearchPlacesTableViewCell안에 static 사용해서 접근해주세요

2023-10-30 00:57 UTC, HJ39 commented on TWTW/TWTW/SearchPlaces/SearchPlaces/SearchPlacesMapViewController.swift
> +    let searchPlacesTableViewCell = SearchPlacesTableViewCell()
아니면 enum 사용하는 방법은 어떤가요?

2023-11-07 01:45 UTC, merged